### ISSUE TITLE
Customization support

### ISSUE THREAD

**Issue by joelod** [handplant/craft-geoman#2]
Hi, first of all, thanks for this great CraftCMS plugin.

Is it currently possible to customize the plugin as documented [here](https://www.geoman.io/docs/customize/toolbar)?

Would be great if the plugin accepted options override, similar to for example the CraftCMS Redactor plugin.

What do you think?

**Comment by handplant** [comment]
I'm glad you like it. Unfortunately, I currently don't have the time to extend the plugin. Feel free to fork the repo to implement your requirements. I apologize.
